name = "Lattice2D"
uuid = "e8031020-b7ff-4f1d-bee4-f79aea4cf140"
version = "0.1.0"
authors = ["souta "]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
LinearAlgebra = "1.12.0"
Plots = "1.41.2"
Test = "1.11.0"
